### ISSUE TITLE
Resubmission Checklist

### ISSUE THREAD

**Issue by lizcramerfox** [lizcramerfox/family-archive-client#31]
### README.md:
- [x] Both READMEs should have an explanation of the what the app does and how it works.
- [x] Both READMEs should have a link to the other repo
- [x] Both READMEs should have a link to both deployed sites
- [x] Both READMEs should have a list of technologies used
- [x] Both READMEs should have a ,list unsolved problems which would be fixed in future iterations.
- [x] Both READMEs should document your planning, process and problem-solving strategy
- [x] Your front-end README should link to wireframes and user stories
- [x] Your front-end README should have an embedded screenshot of the app
- [x] Your back-end README should have a link to Entity Relationship Diagram (ERD).
- [x] Your back-end README should have a catalog of routes (paths and methods) that the API expects.
- [x] Your back-end README should have installation instructions for any dependencies

### Auth Specifications:
- [x] Signup with email, password, and password confirmation.
- [x] Logout when logged in.
- [x] Change password with current and new password.
- [x] Give feedback to the user after each action's success or failure.

### Client Specifications
- [x] Use a front-end Javascript app to communicate with your API (both read and write) and render data that it receives in the browser.
- [x] Have semantically clean HTML and CSS

### API Specifications:
- [x] Any actions which change data must be authenticated and the data must be "owned" by the user performing the change.
- [x] Currently anyone can delete or update each other's memories as long as they are signed in
